config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask

  end
  def answer
    @question = params[:question] if params[:question].present?
    @answer = "I don't care, get dressed and go to work!"
    @answer = 'Great!' if @question == 'I am going to work'
    @answer = 'Silly question, get dressed and go to work!' if @question[-1] == "?"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="title">Stupid Coaching</h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<form action="/ask">
  <div class="question-container">
    <p><%= params[:question] %></p>
    <p class="cursive">- You</p>
  </div>
  <div class="answer-container">
    <p><%=@answer%></p>
    <p class="cursive">- Your Coach</p>
  </div>
  <%= button_to "Click here to ask another question", ask_url, class: "btn btn-danger", :method => "get"%>
</form>

app/views/questions/ask.html.erb
<form class ="form-group" action="/answer">
<p class="cursive">Ask your coach anything</p>
  <div class="formbox">
    <input class="input-group-text" type="text" name="question">
    <input class="btn btn-primary" type="submit" value="Ask!">
  </div>
</form>